export const SHUFFLE = "SHUFFLE";
export type SHUFFLE = typeof SHUFFLE;

export const CHANGE_FONT = "CHANGE_FONT";
export type CHANGE_FONT = typeof CHANGE_FONT;

export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;